### Plugin Catcher
#
# Leave this untouched unless a developer or instructed to change this
#
# If true (default), displays issues that could lead to a server-crashing ConcurrentModificationException
# If false (spammy), displays the above PLUS things that could be bad for the async thread.
#
onlydangerous: true